name: ✅ PR Status Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ PR check complete
        run: echo "PR check passed"
